spring.application.name=ramkflix

spring.datasource.url=jdbc:mysql://localhost:3306/ramflix
spring.datasource.username=root
spring.datasource.password=Parama@57681

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cloudinary.cloud-name=dnd50doyj
cloudinary.api-key=198793424723141
cloudinary.api-secret=puBK-XkmAzrpxX74ubScPEOvoAw

spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB